### ISSUE TITLE
assoc is obsolete(!)

### ISSUE THREAD

**Issue by BeSlayed** [christopherjwhite/org-toodledo#10]
I get the warning "assoc is obsolete!" when I run org-toodledo under Emacs 24. Is there a fix?

**Comment by christopherjwhite** [comment]
Version 2.9 removes references to assoc.el, uses local variations of aput/adelete.  What a pain...

**Comment by BeSlayed** [comment]
Thanks. Actually 24.1 doesn't seem to complain, but the snapshot versions do/did.

**Comment by christopherjwhite** [comment]
Yeah -- after a bit of googling, it seems assoc.el was not liked and was 
soon to go away.  I found it a bit frustrating that there were no clear 
examples of how best to replace aput/adelete, as those were the ones I 
needed.  I gathered their existing implementations were not liked 
because of performance.  Seems some folks suggested moving to plists, 
but part of the problem is that alists did not actually go away, just 
the helper functions defined in assoc.el!

Thanks for reporting it!

...cj
