### ISSUE TITLE
Excessive Tokens

### ISSUE THREAD

**Issue by lawlist** [christopherjwhite/org-toodledo#19]
I'm experiencing a shutdown by Toodledo due to Excessive Tokens.  Essentially, I can only run about 10 tests of 10 tasks before being locked out for an hour.  According to someone "in the know" on the Toodledo Forum, it is possible for a 3rd party app to synchronize without the Excessive Tokens error.

This issue occurs even with creating a blank org file and synchronizing about 10 times from Toodledo to a blank file.  E.g., blank org file, synchronize, exit Emacs without saving, and repeat the process with a blank org file, and on about the 10th synchronization, Excessive Tokens causes a lockout with Toodledo servers.

**Comment by christopherjwhite** [comment]
Toodledo has always had a token limit -- a client can only request up to 10 tokens per hour.  If you have a long running emacs session, it will only request tokens as needed (on startup, then later on expiration).  When you exit emacs, the token is lost.  That's why you're seeing the problem with a blank file.  You're hitting the 10 token limit.

See: http://api.toodledo.com/2/account/doc_sync.php

I noticed an additional limit of 250 requests/hour.  That seems like enough, but I could see hitting that as well under significant testing.  

This was one of the reasons I implemented the "simulation" mode.  It runs a separate set of tests against simulated server implemented in elisp as well.  It's useful when making changes to how the code runs and validating that it did not break anything.  It supports most functionality of the server, but not entirely.

Can you post a reference to forum post indicating getting past the excessive tokens error?  I've searched in the past and have only come up with references to the rate limiting and the need for clients to implement proper caching.

**Comment by lawlist** [comment]
It is just a thread of a few posts by me whimpering about the Excessive Tokens issue, and the Toodledo Admin explaining initially that it is the user's problem and then later acknowledging that their token limit is needed to keep their service from getting overloaded.  Your explanation was very helpful -- thank you very much.

http://www.toodledo.com/forums/2/17455/-2/could-not-log-in-to-toodledo-excessive-tokens.html#end

**Comment by lawlist** [comment]
By using the function`M-x load-library` subsequent to each modification of a library (e.g., `org-toodledo.el`) , a user can keep Emacs open without requesting a new token -- unless the core functionality is being tweaked.
