### ISSUE TITLE
Can't get subtasks to work

### ISSUE THREAD

**Issue by mitnworb** [christopherjwhite/org-toodledo#20]
They just show up flat.  I have a pro toodledo account.  I am able to nest tasks in toodledo webapp.  Any Ideas?

I have my setup like this:
- Tasks
  *\* Todo
  *\* Todo
  *\* Todo
  *\* Todo
- Projects
  *\* Project1
  **\* Todo
  **\* Todo
  *\* project2
  **\* Todo
  **\* Todo

**Comment by christopherjwhite** [comment]
The markup got a little messed up, but I think I see the problem.  org-toodledo only recognizes items with a TODO status as status.  This matches the way Toodledo handles it as well, the parent task can have a separate status from child tasks.  SO, you need to add one of the TODO keywords to what you'd like the parent to be.  Since only one level of hierarchy is supported by Toodledo, that would be something like:

```
* TODO Tasks
** TODO Task
** TODO Task
* Projects
** TODO Project 1
*** TODO Task
*** TODO Task
** TODO Project 2
*** TODO Task
*** TODO Task
```

In the above, the only line that will _not_ show up in Toodledo is the "Projects" line, as it has no TODO keyword.

Let me know if that takes care of it for you.

**Comment by christopherjwhite** [comment]
Closing this issue for now, as I don't think there is a bug here, just a misunderstanding of how sub-tasks work.   Please re-open if you find you still cannot get this to work.
